services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # The 'environment' block now uses variables that Docker Compose
    # will pull from the .env file.
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # This 'env_file' directive makes all variables from .env
    # available inside the 'web' container.
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data:
