# Generated by Django 5.2.7 on 2025-10-07 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A unique title for the problem', max_length=200, unique=True)),
                ('description', models.TextField(help_text='The markdown description of the SQL problem.')),
                ('solution_explanation', models.TextField(help_text='The detailed, step-by-step breakdown of the solution logic.')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='The correct SQL query to solve the problem.')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='practice.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(help_text='The CREATE TABLE and INSERT INTO statements for one table.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which schema scripts should be executed for a problem.')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='practice.problem')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('problem', 'order')},
            },
        ),
    ]
